{"name": "Проверка невозможности удаления курьера при неполном запросе", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 400)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_courier.TestCourierDelete object at 0x104c58a40>\n\n    @allure.title('Проверка невозможности удаления курьера при неполном запросе')\n    @allure.description('При удалении курьера не передается \"id\"')\n    # тут тест будет падать так как кажется в API есть баги\n    def test_courier_delete_no_id_error_message(self):\n        response = requests.delete('http://qa-scooter.praktikum-services.ru/api/v1/courier/')\n>       assert response.status_code == 400 and response.json()['message'] == 'Недостаточно данных для удаления курьера'\nE       assert (404 == 400)\nE        +  where 404 = <Response [404]>.status_code\n\ntests/test_courier.py:136: AssertionError"}, "description": "При удалении курьера не передается \"id\"", "start": 1709833422439, "stop": 1709833422630, "uuid": "0adb0e86-d606-4de5-ba3e-9c1297b4c7b8", "historyId": "9067889620498e266873c56ac0e9cea5", "testCaseId": "9067889620498e266873c56ac0e9cea5", "fullName": "tests.test_courier.TestCourierDelete#test_courier_delete_no_id_error_message", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierDelete"}, {"name": "host", "value": "Radiuss-MacBook-Air.local"}, {"name": "thread", "value": "79342-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}